[build-system]
requires = [
  "scikit-build-core>=0.10",
  "nanobind>=2.4",
]
build-backend = "scikit_build_core.build"

[project]
name = "spcraft"
version = "0.0.1"
description = "Optional Python interface for the SPCraft C++ library"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = { file = "LICENSE" }
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=1.23",
    "scipy>=1.13.1",
]

[tool.scikit-build]
cmake.build-type = "Release"
wheel.packages = ["python/spcraft"]

[tool.scikit-build.cmake.define]
SPCRAFT_BUILD_EXAMPLES = "OFF"
SPCRAFT_BUILD_PYTHON = "ON"

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
    "jupyter>=1.0.0",
    "matspy>=1.0.0",
    "nanobind>=2.4",
    "networkx>=3.4",
    "pytest>=8.4.2",
]
